name: Push Flow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint Step
              run: npm run lint
            - name: Test Step
              run: npm run test
            - name: Build Step
              run: npm run build